INSERT INTO book (title, description, page_count)
VALUES ('The Great Gatsby', 'A classic novel', 180),
	   ('To Kill a Mockingbird', 'Story of racial injustice', 281),
	   ('1984', 'Dystopian future', 328),
	   ('Pride and Prejudice', 'Romantic novel', 279),
	   ('Moby Dick', 'Whale hunting adventure', 635),
	   ('War and Peace', 'Historical novel', 1225),
	   ('The Catcher in the Rye', 'Teenage angst', 277),
	   ('The Hobbit', 'Fantasy adventure', 310),
	   ('Crime and Punishment', 'Philosophical novel', 671),
	   ('Anna Karenina', 'Tragic love story', 864),
	   ('Brave New World', 'Dystopian science fiction', 268),
	   ('The Lord of the Rings', 'Epic fantasy novel', 1178),
	   ('The Adventures of Sherlock Holmes', 'Detective stories', 307),
	   ('The Brothers Karamazov', 'Philosophical drama', 824),
	   ('Frankenstein', 'Science fiction horror', 280),
	   ('Dracula', 'Gothic horror novel', 418),
	   ('The Odyssey', 'Epic Greek poem', 541),
	   ('Ulysses', 'Stream of consciousness novel', 730),
	   ('The Iliad', 'Epic poem of Trojan War', 683),
	   ('Don Quixote', 'Comic novel about a knight', 982);