INSERT INTO book (title, description, page_count) VALUES
('Adventures of Time', 'A thrilling journey', 350),
('Mystic River', 'A tale of suspense', 300),
('The Wanderer', 'An epic tale of adventure', 400),
('Journey to the Unknown', 'Explore the unknown', 270),
('Whispers of the Past', 'Unraveling ancient secrets', 320),
('Echoes of Eternity', 'The battle for immortality', 410),
('The Lost Chronicles', 'Discover hidden truths', 380),
('Realm of Shadows', 'A world of dark mysteries', 290),
('Secrets of the Mind', 'A psychological thriller', 310),
('The Endless Horizon', 'A quest beyond limits', 250),
('Guardian of the Forest', 'Protecting the green heart', 300),
('Storm over the Hills', 'Weathering life’s challenges', 340),
('Legends of the North', 'Epic tales of bravery', 280),
('The Last Voyage', 'An adventurer’s final journey', 360),
('Song of the Waves', 'Romance by the sea', 230),
('Wings of Fire', 'Rising from ashes', 280),
('The Hidden Vault', 'Unearthing lost treasures', 290),
('Dance of the Spirits', 'Tales of otherworldly grace', 260),
('Tales of the Crescent Moon', 'Mysteries under the stars', 270),
('The Crimson Blade', 'Stories of a heroic knight', 310),
('Beneath the Silver Sky', 'A love story under the stars', 220),
('Labyrinth of Souls', 'A journey through the unknown', 330),
('Shadows of the Empire', 'Political intrigue at its best', 350),
('The Phantom King', 'A legend reborn', 370),
('Echoes in the Valley', 'A journey of rediscovery', 290),
('Songs of the Heart', 'A poet’s masterpiece', 260),
('Footsteps in the Sand', 'Memories of a lifetime', 340),
('A Tale of Two Heroes', 'An epic tale of friendship', 380),
('The Edge of Reality', 'A battle between worlds', 310),
('Heart of the Storm', 'Surviving nature’s fury', 300),
('Fires of Destiny', 'Fate’s inevitable call', 360),
('The Golden City', 'Dreams of utopia', 340),
('Voices of the Ocean', 'The mysteries of the deep', 280),
('The Ivory Tower', 'A scholar’s lifelong pursuit', 310),
('Land of Forgotten Dreams', 'Resurrecting lost hopes', 330),
('Chronicles of the Brave', 'Tales of valor and glory', 370),
('The Painted Horizon', 'Art and life intertwined', 260),
('The Clockmaker’s Secret', 'Mystery and time', 320),
('Beyond the Veil', 'A world unseen', 280),
('Threads of Time', 'Weaving the past and future', 350),
('A Glimpse of Infinity', 'A philosophical journey', 300),
('Guardian of the Gate', 'A legendary protector', 310),
('Paths Untraveled', 'Finding new beginnings', 270),
('Shadow of the Wolf', 'A hunter’s story', 280),
('The Silver Compass', 'A guide to the unknown', 290),
('Tides of Change', 'Ebb and flow of life', 250),
('The Hidden Path', 'Secrets of an ancient trail', 310),
('The Sapphire Crown', 'Quest for a legendary treasure', 370),
('The Falling Star', 'A story of hope and redemption', 280),
('Dawn of the Phoenix', 'Rising from the ashes of despair', 330),
('Tales of the Forgotten', 'Stories of lost souls', 310),
('The Celestial Clockwork', 'The universe’s mysteries unraveled', 360),
('Rise of the Titans', 'A battle of epic proportions', 400),
('The Midnight Journey', 'Dreams and reality collide', 320),
('A Realm Beyond', 'A portal to another world', 310),
('Legacy of the Ancients', 'The past shaping the future', 300),
('River of Dreams', 'A soothing tale of self-discovery', 230),
('The Alchemist’s Secret', 'Mysteries of transformation', 350),
('The Frozen Kingdom', 'A tale of endurance and hope', 310),
('The Lone Traveler', 'A solitary wanderer’s journey', 290),
('Crown of Shadows', 'A fight for power', 280),
('The Whispering Woods', 'Mysteries among the trees', 320),
('In the Eye of the Storm', 'Weathering life’s tempests', 310),
('Beneath the Surface', 'Uncovering hidden truths', 260),
('The Forsaken Realm', 'A journey of redemption', 330),
('The Eternal Light', 'A story of hope and resilience', 350),
('Winds of Change', 'Embracing a new dawn', 280),
('The Crimson Horizon', 'A tale of epic battles', 400),
('Chronicles of the Wanderer', 'An endless journey', 310),
('Labyrinth of Mirrors', 'A psychological mystery', 300),
('Realm of the Forgotten', 'Reviving ancient legends', 350),
('The Silent Watcher', 'A guardian’s tale', 320),
('The Shattered Crown', 'A fight for the throne', 280),
('The Painted Sky', 'Dreams under a canvas', 240),
('Beyond the Stars', 'The universe within reach', 380),
('The Rising Sun', 'A story of new beginnings', 300),
('Echoes of the Wind', 'A journey of self-discovery', 310),
('The Final Chapter', 'The end of a saga', 290);